In [2]:
# Load the dataset
import pandas as pd
data=pd.read_csv('/content/all_kindle_review .csv')
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [3]:
df=data[['reviewText','rating']]
df.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [4]:
df.shape

(12000, 2)

In [5]:
## Missing Values
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [6]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [7]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [8]:
## Preprocessing And Cleaning

In [9]:
## postive review is 1 and negative review is 0
df['rating']=df['rating'].apply(lambda x:0 if x<3 else 1)

<ipython-input-9-1e5aedecae4a>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating']=df['rating'].apply(lambda x:0 if x<3 else 1)


In [10]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [11]:
## 1. Lower All the cases
df['reviewText']=df['reviewText'].str.lower()

<ipython-input-11-26e5fcb41736>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].str.lower()


In [12]:
df.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [13]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [14]:
from bs4 import BeautifulSoup

In [15]:
## Removing special characters
df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url
df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove any additional spaces
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))

<ipython-input-15-86b4aeb70b16>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
<ipython-input-15-86b4aeb70b16>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
<ipython-input-15-86b4aeb70b16>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row

In [16]:
df.head()

reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [17]:
!pip install nltk # Make sure NLTK is installed
import nltk # Import the NLTK library
nltk.download('wordnet') # Download the 'wordnet' resource

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [18]:
## Lemmatizer
from nltk.stem import WordNetLemmatizer

In [19]:
lemmatizer=WordNetLemmatizer()

In [20]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [21]:
df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

<ipython-input-21-7fa46fdadeba>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))


In [22]:
df.head()

reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [23]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],test_size=0.20)

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

In [26]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [27]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,y_train)

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [29]:
y_pred_bow=nb_model_bow.predict(X_test_bow)

In [30]:
y_pred_tfidf=nb_model_bow.predict(X_test_tfidf)

In [31]:
confusion_matrix(y_test,y_pred_bow)

array([[492, 292],
       [745, 871]])

In [32]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.5679166666666666


In [33]:
confusion_matrix(y_test,y_pred_tfidf)

array([[480, 304],
       [737, 879]])

In [34]:
print("TFIDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))

TFIDF accuracy:  0.56625


In [ ]:
# Word2Vec

In [35]:
!pip install gensim

In [36]:
from gensim.models import Word2Vec
import nltk

In [37]:
# Tokenize the sentences
nltk.download('punkt')
df['tokenized'] = df['reviewText'].apply(nltk.word_tokenize)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
<ipython-input-37-bd3ba2e39ac5>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tokenized'] = df['reviewText'].apply(nltk.word_tokenize)


In [38]:
df.head()

reviewText  rating  \
0  jace rankin may short he nothing mess man haul...       1   
1  great short read didnt want put read one sitti...       1   
2  ill start saying first four book wasnt expecti...       1   
3  aggie angela lansbury carry pocketbook instead...       1   
4  expect type book library pleased find price right       1   

                                           tokenized  
0  [jace, rankin, may, short, he, nothing, mess, ...  
1  [great, short, read, didnt, want, put, read, o...  
2  [ill, start, saying, first, four, book, wasnt,...  
3  [aggie, angela, lansbury, carry, pocketbook, i...  
4  [expect, type, book, library, pleased, find, p...

In [39]:
# Train Word2Vec model
word2vec_model = Word2Vec(df['tokenized'], vector_size=100, window=5, min_count=2, workers=4)

#Trained the Word2Vec model on tokenized Kindle review texts using a 100-dimensional vector space.
#Set a context window of 5 words, filtered out words appearing less than twice, and utilized 4 CPU cores for efficient parallel processing.
#This configuration captured rich semantic relationships in the text data.

In [55]:
import random

# Select a random review from the DataFrame
random_review = df['tokenized'].sample().values[0]

# Select a random word from the tokenized review
random_word = random.choice(random_review)

# Check if the word is in the Word2Vec model's vocabulary
if random_word in word2vec_model.wv:
    # Get the vector representation of the random word
    word_vector = word2vec_model.wv[random_word]
    print(f"Vector representation of the word '{random_word}':\n", word_vector)
else:
    print(f"The word '{random_word}' is not in the Word2Vec model's vocabulary.")


Vector representation of the word 'recommend':
 [-0.32041234 -0.07244577 -0.13193916  0.35615602  0.53831804 -1.0753475
  1.058097    1.9746958  -1.5421877   1.0576512  -0.8856601  -0.7480014
 -1.2862213   0.49114886 -1.3142751   0.30264091  0.0196328  -0.6865881
 -2.0948331  -2.5347416  -1.3122859   0.14342691  0.9199456  -0.38715458
  1.2444028  -1.4011289  -0.34129372 -0.08605523 -1.6089699   0.8624231
  1.8243145  -0.49777237  1.8593479  -0.91578007 -1.5433865   1.1930461
 -0.0772447  -0.5862146  -1.3810196  -1.8352172  -0.05484694 -1.0455173
  1.4893771  -0.84435767  2.3883913   0.76951504 -0.61039716 -0.33229193
  0.21735722  2.171541    0.0209764   0.36591658  0.27822533 -0.03204535
 -1.0681462  -0.8911571   0.6580428   0.9357586  -1.0020597   1.8072591
 -0.06347612 -0.6771787   1.5318931   0.41689566 -0.862214    0.38913813
  0.51854867 -0.30876994 -1.0230978   0.93176615  0.03845335  1.1917611
 -0.63480264  0.25499776  2.2701423  -1.5917546   0.8397005  -0.5356391
 -0.73004395

In [41]:
word_vector.shape

(100,)

In [42]:
import numpy as np

In [43]:
#Generate Word2Vec Features
def vectorize_review(review):
    words = [word for word in review if word in word2vec_model.wv]
    if len(words) > 0:
        return np.mean(word2vec_model.wv[words], axis=0)
    else:
        return np.zeros(100)  # Return a vector of zeros if the review is empty after tokenization

#The `vectorize_review` function converts a review into a 100-dimensional vector by averaging Word2Vec embeddings of the review's words.
#It handles words not in the model's vocabulary by returning a zero vector. This vector representation is then used to train and test machine learning models.

In [44]:
# Apply the vectorization to both train and test data
X_train_w2v = np.array([vectorize_review(review) for review in df['tokenized'][X_train.index]])
X_test_w2v = np.array([vectorize_review(review) for review in df['tokenized'][X_test.index]])

In [45]:
# Train the model using Word2Vec features
nb_model_w2v = GaussianNB().fit(X_train_w2v, y_train)

In [46]:
# Predict and evaluate
y_pred_w2v = nb_model_w2v.predict(X_test_w2v)

In [47]:
print(confusion_matrix(y_test, y_pred_w2v))

[[ 558  226]
 [ 505 1111]]


In [48]:
# Confusion Matrix and Accuracy
print("Word2Vec accuracy: ", accuracy_score(y_test, y_pred_w2v))

Word2Vec accuracy:  0.6954166666666667


Comparing the performance of the Word2Vec, Bag-of-Words (BOW) and TF-IDF models.

In [49]:
import pandas as pd

In [50]:
# Calculate Accuracies
bow_accuracy = accuracy_score(y_test, y_pred_bow)
tfidf_accuracy = accuracy_score(y_test, y_pred_tfidf)
w2v_accuracy = accuracy_score(y_test, y_pred_w2v)

In [51]:
# Create a DataFrame to display the accuracies
accuracy_df = pd.DataFrame({
    'Model': ['Bag of Words', 'TF-IDF', 'Word2Vec'],
    'Accuracy': [bow_accuracy, tfidf_accuracy, w2v_accuracy]
})

In [52]:
# Display the accuracies in a neat table
print("\n### Model Accuracies ###\n")
print(accuracy_df)


### Model Accuracies ###

          Model  Accuracy
0  Bag of Words  0.567917
1        TF-IDF  0.566250
2      Word2Vec  0.695417


In [53]:
# Compute Confusion Matrices
conf_matrix_bow = confusion_matrix(y_test, y_pred_bow)
conf_matrix_tfidf = confusion_matrix(y_test, y_pred_tfidf)
conf_matrix_w2v = confusion_matrix(y_test, y_pred_w2v)

In [54]:
# Display Confusion Matrices with headings
print("\n### Confusion Matrices ###\n")

print("\nBag of Words Confusion Matrix:\n", conf_matrix_bow)
print("\nTF-IDF Confusion Matrix:\n", conf_matrix_tfidf)
print("\nWord2Vec Confusion Matrix:\n", conf_matrix_w2v)


### Confusion Matrices ###


Bag of Words Confusion Matrix:
 [[492 292]
 [745 871]]

TF-IDF Confusion Matrix:
 [[480 304]
 [737 879]]

Word2Vec Confusion Matrix:
 [[ 558  226]
 [ 505 1111]]
